# Generated by Django 6.0.1 on 2026-05-03 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionCorreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Convocatoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Convocatoria al Forum de Ciencias Técnicas e Innovación de Desoft Santiago de Cuba', max_length=200)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_cierre', models.DateTimeField()),
                ('objetivos', models.TextField()),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoPlantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('ponencia', 'Plantilla de Ponencia'), ('ficha_tecnica', 'Formulario de Ficha Técnica'), ('aval', 'Formulario de Aval')], max_length=20)),
                ('archivo', models.FileField(upload_to='plantillas/')),
                ('descripcion', models.TextField()),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MiembroComision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('preside_comite', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ParticipanteForum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200)),
                ('carne_identidad', models.CharField(max_length=11, unique=True)),
                ('categoria_ocupacional', models.CharField(choices=[('trabajador', 'Trabajador'), ('colaborador_externo', 'Colaborador Externo'), ('estudiante', 'Estudiante'), ('otro', 'Otro')], max_length=20)),
                ('centro_trabajo', models.CharField(max_length=200)),
                ('contacto', models.CharField(max_length=100)),
                ('relacion_empresa', models.CharField(choices=[('trabajador', 'Trabajador'), ('colaborador', 'Colaborador'), ('estudiante', 'Estudiante'), ('externo', 'Externo')], max_length=20)),
                ('ponencia', models.FileField(upload_to='ponencias/%Y/%m/%d/')),
                ('ficha_tecnica', models.FileField(upload_to='fichas_tecnicas/%Y/%m/%d/')),
                ('avales', models.FileField(upload_to='avales/%Y/%m/%d/')),
                ('presentacion', models.FileField(upload_to='presentaciones/%Y/%m/%d/')),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('numero_expediente', models.CharField(blank=True, max_length=20, unique=True)),
                ('evaluado', models.BooleanField(default=False)),
                ('aceptado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramaForum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.CharField(max_length=100)),
                ('actividad', models.CharField(max_length=200)),
                ('responsable', models.CharField(max_length=100)),
                ('trabajo', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResumenInnovacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.IntegerField()),
                ('categoria', models.CharField(max_length=100)),
                ('trabajo', models.CharField(max_length=200)),
                ('reconocimiento', models.CharField(blank=True, max_length=200, null=True)),
                ('gasto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('participantes', models.TextField(blank=True, help_text='Nombres de los participantes', null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Resúmenes de innovación',
                'ordering': ['-año', 'categoria'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudVentanilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('proyecto', 'Solicitud de Proyecto'), ('demanda', 'Demanda Tecnológica'), ('empleo', 'Solicitud de Empleo')], max_length=20)),
                ('estado', models.CharField(choices=[('recibida', 'Recibida'), ('en_revision', 'En Revisión'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], default='recibida', max_length=20)),
                ('nombre_contacto', models.CharField(max_length=200)),
                ('empresa', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('nombre_proyecto', models.CharField(blank=True, max_length=200)),
                ('descripcion', models.TextField()),
                ('area_interes', models.CharField(blank=True, max_length=200)),
                ('documentacion', models.FileField(blank=True, null=True, upload_to='ventanilla/%Y/%m/')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('numero_expediente', models.CharField(blank=True, max_length=20, unique=True)),
            ],
            options={
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='TrabajoInnovacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.IntegerField()),
                ('categoria', models.CharField(max_length=100)),
                ('trabajo', models.CharField(max_length=200)),
                ('reconocimiento', models.CharField(blank=True, max_length=200, null=True)),
                ('gasto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BancoProblema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.IntegerField()),
                ('numero', models.IntegerField()),
                ('objetivo', models.TextField()),
                ('problema', models.TextField()),
                ('ponencia_consultar', models.CharField(blank=True, max_length=200, null=True)),
                ('prioridad', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=10)),
                ('resuelto', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-año', 'numero'],
                'unique_together': {('año', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('convocatoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='emprendedores.convocatoria')),
            ],
        ),
        migrations.CreateModel(
            name='GestorCiencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('grado_academico', models.CharField(choices=[('tecnico', 'Técnico'), ('licenciatura', 'Licenciatura'), ('maestria', 'Maestría'), ('doctorado', 'Doctorado')], max_length=20)),
                ('institucion', models.CharField(max_length=100)),
                ('especialidades', models.TextField()),
                ('experiencia', models.TextField()),
                ('areas_tutorizar', models.TextField(help_text='Lista de áreas en las que puede tutorizar')),
                ('max_proyectos', models.PositiveIntegerField(default=3)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmprendedorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emprendedor_profile', to=settings.AUTH_USER_MODEL)),
                ('gestor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emprendedores_asignados', to='emprendedores.gestorciencias')),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_destinatario', models.CharField(choices=[('gestor', 'Gestor de Ciencias'), ('emprendedor', 'Emprendedor'), ('administrador', 'Administrador')], max_length=20)),
                ('asunto', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('leido', models.BooleanField(default=False)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='mensajes/%Y/%m/%d/')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_recibidos', to=settings.AUTH_USER_MODEL)),
                ('remitente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_enviados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='Comision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('integrantes', models.ManyToManyField(blank=True, related_name='comisiones', to='emprendedores.miembrocomision')),
                ('presidente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comisiones_presididas', to='emprendedores.miembrocomision')),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proyecto', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('nombre_completo', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('revision', 'En revisión'), ('aceptado', 'Aceptado'), ('asignado', 'En proceso'), ('rechazado', 'Rechazado'), ('finalizado', 'Finalizado')], default='pendiente', max_length=20)),
                ('sector', models.CharField(choices=[('tecnologia', 'Tecnología'), ('salud', 'Salud'), ('educacion', 'Educación'), ('finanzas', 'Finanzas'), ('comercio', 'Comercio'), ('otros', 'Otros')], default='tecnologia', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('archivo_proyecto', models.FileField(blank=True, null=True, upload_to='proyectos/%Y/%m/%d/')),
                ('progreso', models.PositiveIntegerField(default=0)),
                ('motivo_rechazo', models.TextField(blank=True, null=True)),
                ('presupuesto_estimado', models.DecimalField(blank=True, decimal_places=2, help_text='Presupuesto estimado del proyecto en pesos', max_digits=12, null=True)),
                ('gestor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos_gestionados', to='emprendedores.gestorciencias')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='SesionMentoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_propuesta', models.DateTimeField()),
                ('duracion', models.PositiveIntegerField(help_text='Duración en minutos')),
                ('formato', models.CharField(choices=[('virtual', 'Virtual'), ('presencial', 'Presencial'), ('hibrido', 'Híbrido')], default='virtual', max_length=10)),
                ('enlace_virtual', models.URLField(blank=True, null=True)),
                ('direccion_presencial', models.CharField(blank=True, max_length=255, null=True)),
                ('objetivo', models.CharField(max_length=200)),
                ('agenda', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('draft', 'Borrador'), ('propuesta', 'Propuesta'), ('pendiente_confirmacion', 'Pendiente de Confirmación'), ('confirmada', 'Confirmada'), ('reprogramacion_solicitada', 'Reprogramación Solicitada'), ('rescheduled', 'Reprogramada'), ('cancelada', 'Cancelada'), ('realizada', 'Realizada'), ('no_show', 'No Show'), ('blocked', 'Bloqueada')], default='draft', max_length=30)),
                ('tipo', models.CharField(choices=[('revision_inicial', 'Revisión Inicial'), ('seguimiento', 'Seguimiento'), ('presentacion_avance', 'Presentación de Avance'), ('problematica', 'Resolución de Problemática'), ('otro', 'Otro')], default='seguimiento', max_length=20)),
                ('materiales_requeridos', models.TextField(blank=True, help_text='Lista de materiales requeridos')),
                ('es_material_obligatorio', models.BooleanField(default=False)),
                ('motivo_cancelacion', models.TextField(blank=True)),
                ('motivo_rechazo', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_ultima_modificacion', models.DateTimeField(auto_now=True)),
                ('contador_reprogramaciones', models.PositiveIntegerField(default=0)),
                ('gestor_presente', models.BooleanField(default=False)),
                ('emprendedor_presente', models.BooleanField(default=False)),
                ('minuta', models.TextField(blank=True)),
                ('creada_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_creadas', to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='emprendedores.proyecto')),
                ('sesion_original', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reprogramaciones', to='emprendedores.sesionmentoria')),
            ],
            options={
                'ordering': ['fecha_propuesta'],
            },
        ),
        migrations.CreateModel(
            name='PropuestaHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_propuesta', models.DateTimeField()),
                ('duracion', models.PositiveIntegerField(default=60)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('mensaje', models.TextField(blank=True)),
                ('aceptada', models.BooleanField(default=False)),
                ('propuesto_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propuestas_horario', to='emprendedores.sesionmentoria')),
            ],
            options={
                'ordering': ['fecha_propuesta'],
            },
        ),
        migrations.CreateModel(
            name='EventoSesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('detalles', models.TextField(blank=True)),
                ('estado_anterior', models.CharField(blank=True, max_length=30)),
                ('estado_nuevo', models.CharField(blank=True, max_length=30)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='emprendedores.sesionmentoria')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ArchivoSesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='materiales_sesiones/%Y/%m/%d/')),
                ('fecha_subido', models.DateTimeField(auto_now_add=True)),
                ('es_material_obligatorio', models.BooleanField(default=False)),
                ('subido_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='emprendedores.sesionmentoria')),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('prioridad', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_limite', models.DateTimeField()),
                ('completada', models.BooleanField(default=False)),
                ('asignada_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas_asignadas', to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='emprendedores.proyecto')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
