# Generated by Django 6.0.1 on 2026-05-19 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprendedores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesionmentoria',
            name='tipo',
            field=models.CharField(choices=[('problematica', 'Resolución de Problemática'), ('seguimiento', 'Seguimiento'), ('otro', 'Otro'), ('revision_inicial', 'Revisión Inicial'), ('presentacion_avance', 'Presentación de Avance')], default='seguimiento', max_length=20),
        ),
    ]
