# Generated by Django 6.0.1 on 2026-02-19 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprendedores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='presupuesto_estimado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Presupuesto estimado del proyecto en pesos', max_digits=12, null=True),
        ),
    ]
