# Generated by Django 6.0.1 on 2026-04-12 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprendedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudVentanilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('proyecto', 'Solicitud de Proyecto'), ('demanda', 'Demanda Tecnológica'), ('empleo', 'Solicitud de Empleo')], max_length=20)),
                ('estado', models.CharField(choices=[('recibida', 'Recibida'), ('en_revision', 'En Revisión'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], default='recibida', max_length=20)),
                ('nombre_contacto', models.CharField(max_length=200)),
                ('empresa', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('nombre_proyecto', models.CharField(blank=True, max_length=200)),
                ('descripcion', models.TextField()),
                ('area_interes', models.CharField(blank=True, max_length=200)),
                ('documentacion', models.FileField(blank=True, null=True, upload_to='ventanilla/%Y/%m/')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('numero_expediente', models.CharField(blank=True, max_length=20, unique=True)),
            ],
            options={
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
