# Generated by Django 6.0.1 on 2026-02-26 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprendedores', '0002_proyecto_presupuesto_estimado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('revision', 'En revisión'), ('aceptado', 'Aceptado'), ('asignado', 'En proceso'), ('rechazado', 'Rechazado'), ('finalizado', 'Finalizado')], default='pendiente', max_length=20),
        ),
    ]
