# Generated by Django 6.0.1 on 2026-02-26 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprendedores', '0003_alter_proyecto_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='mensajes/%Y/%m/%d/'),
        ),
    ]
